config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  resources :categories
  devise_for :users, :controllers => {sessions: 'users/sessions'}

  resources :account_transactions, only: [:create]

  root 'pages#index'

  resources :devise_logs, only: [:index]

  get '/profile' => 'users#profile', :as => :profile

end

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Productivity Optimizer', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          =link_to 'Categories', categories_path
        %li
          =link_to 'Accounts', accounts_path
        %li
          =link_to 'Session Logs', devise_logs_path
      %ul.nav.navbar-nav.pull-right
        = render 'layouts/navigation_links'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Finance Journal'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Finance Journal'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      .unobtrusive-flash-container
      = yield
  =render 'pages/login_modal'
  =render 'pages/sign_up_modal'